// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FitnessDataPointDataType.
const (
	ActiveMinutes FitnessDataPointDataType = "active_minutes"
	Calories      FitnessDataPointDataType = "calories"
	Distance      FitnessDataPointDataType = "distance"
	HeartRate     FitnessDataPointDataType = "heart_rate"
	Sleep         FitnessDataPointDataType = "sleep"
	Steps         FitnessDataPointDataType = "steps"
)

// Valid indicates whether the value is a known member of the FitnessDataPointDataType enum.
func (e FitnessDataPointDataType) Valid() bool {
	switch e {
	case ActiveMinutes:
		return true
	case Calories:
		return true
	case Distance:
		return true
	case HeartRate:
		return true
	case Sleep:
		return true
	case Steps:
		return true
	default:
		return false
	}
}

// Defines values for FitnessDataPointSource.
const (
	GoogleFit     FitnessDataPointSource = "google_fit"
	HealthConnect FitnessDataPointSource = "health_connect"
)

// Valid indicates whether the value is a known member of the FitnessDataPointSource enum.
func (e FitnessDataPointSource) Valid() bool {
	switch e {
	case GoogleFit:
		return true
	case HealthConnect:
		return true
	default:
		return false
	}
}

// Defines values for FitnessDataPointUnit.
const (
	Bpm     FitnessDataPointUnit = "bpm"
	Count   FitnessDataPointUnit = "count"
	Kcal    FitnessDataPointUnit = "kcal"
	Meters  FitnessDataPointUnit = "meters"
	Minutes FitnessDataPointUnit = "minutes"
)

// Valid indicates whether the value is a known member of the FitnessDataPointUnit enum.
func (e FitnessDataPointUnit) Valid() bool {
	switch e {
	case Bpm:
		return true
	case Count:
		return true
	case Kcal:
		return true
	case Meters:
		return true
	case Minutes:
		return true
	default:
		return false
	}
}

// Defines values for HealthCheckInResponseEnergyLevel.
const (
	High   HealthCheckInResponseEnergyLevel = "high"
	Low    HealthCheckInResponseEnergyLevel = "low"
	Medium HealthCheckInResponseEnergyLevel = "medium"
)

// Valid indicates whether the value is a known member of the HealthCheckInResponseEnergyLevel enum.
func (e HealthCheckInResponseEnergyLevel) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for HealthCheckInResponseMedicationTaken.
const (
	No      HealthCheckInResponseMedicationTaken = "no"
	Partial HealthCheckInResponseMedicationTaken = "partial"
	Yes     HealthCheckInResponseMedicationTaken = "yes"
)

// Valid indicates whether the value is a known member of the HealthCheckInResponseMedicationTaken enum.
func (e HealthCheckInResponseMedicationTaken) Valid() bool {
	switch e {
	case No:
		return true
	case Partial:
		return true
	case Yes:
		return true
	default:
		return false
	}
}

// Defines values for HealthCheckInResponseMood.
const (
	Negative HealthCheckInResponseMood = "negative"
	Neutral  HealthCheckInResponseMood = "neutral"
	Positive HealthCheckInResponseMood = "positive"
)

// Valid indicates whether the value is a known member of the HealthCheckInResponseMood enum.
func (e HealthCheckInResponseMood) Valid() bool {
	switch e {
	case Negative:
		return true
	case Neutral:
		return true
	case Positive:
		return true
	default:
		return false
	}
}

// Defines values for HealthCheckInResponseSleepQuality.
const (
	Excellent HealthCheckInResponseSleepQuality = "excellent"
	Fair      HealthCheckInResponseSleepQuality = "fair"
	Good      HealthCheckInResponseSleepQuality = "good"
	Poor      HealthCheckInResponseSleepQuality = "poor"
)

// Valid indicates whether the value is a known member of the HealthCheckInResponseSleepQuality enum.
func (e HealthCheckInResponseSleepQuality) Valid() bool {
	switch e {
	case Excellent:
		return true
	case Fair:
		return true
	case Good:
		return true
	case Poor:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusDatabase.
const (
	Connected    HealthStatusDatabase = "connected"
	Disconnected HealthStatusDatabase = "disconnected"
)

// Valid indicates whether the value is a known member of the HealthStatusDatabase enum.
func (e HealthStatusDatabase) Valid() bool {
	switch e {
	case Connected:
		return true
	case Disconnected:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	Healthy   HealthStatusStatus = "healthy"
	Unhealthy HealthStatusStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// Defines values for MenstruationRequestFlowIntensity.
const (
	MenstruationRequestFlowIntensityHeavy    MenstruationRequestFlowIntensity = "heavy"
	MenstruationRequestFlowIntensityLight    MenstruationRequestFlowIntensity = "light"
	MenstruationRequestFlowIntensityModerate MenstruationRequestFlowIntensity = "moderate"
)

// Valid indicates whether the value is a known member of the MenstruationRequestFlowIntensity enum.
func (e MenstruationRequestFlowIntensity) Valid() bool {
	switch e {
	case MenstruationRequestFlowIntensityHeavy:
		return true
	case MenstruationRequestFlowIntensityLight:
		return true
	case MenstruationRequestFlowIntensityModerate:
		return true
	default:
		return false
	}
}

// Defines values for MenstruationResponseFlowIntensity.
const (
	MenstruationResponseFlowIntensityHeavy    MenstruationResponseFlowIntensity = "heavy"
	MenstruationResponseFlowIntensityLight    MenstruationResponseFlowIntensity = "light"
	MenstruationResponseFlowIntensityModerate MenstruationResponseFlowIntensity = "moderate"
)

// Valid indicates whether the value is a known member of the MenstruationResponseFlowIntensity enum.
func (e MenstruationResponseFlowIntensity) Valid() bool {
	switch e {
	case MenstruationResponseFlowIntensityHeavy:
		return true
	case MenstruationResponseFlowIntensityLight:
		return true
	case MenstruationResponseFlowIntensityModerate:
		return true
	default:
		return false
	}
}

// Defines values for ReportResponseStatus.
const (
	ReportResponseStatusCompleted  ReportResponseStatus = "completed"
	ReportResponseStatusFailed     ReportResponseStatus = "failed"
	ReportResponseStatusGenerating ReportResponseStatus = "generating"
)

// Valid indicates whether the value is a known member of the ReportResponseStatus enum.
func (e ReportResponseStatus) Valid() bool {
	switch e {
	case ReportResponseStatusCompleted:
		return true
	case ReportResponseStatusFailed:
		return true
	case ReportResponseStatusGenerating:
		return true
	default:
		return false
	}
}

// Defines values for SessionResponseStatus.
const (
	SessionResponseStatusActive    SessionResponseStatus = "active"
	SessionResponseStatusCompleted SessionResponseStatus = "completed"
	SessionResponseStatusExpired   SessionResponseStatus = "expired"
)

// Valid indicates whether the value is a known member of the SessionResponseStatus enum.
func (e SessionResponseStatus) Valid() bool {
	switch e {
	case SessionResponseStatusActive:
		return true
	case SessionResponseStatusCompleted:
		return true
	case SessionResponseStatusExpired:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatusStatus.
const (
	Active    SessionStatusStatus = "active"
	Completed SessionStatusStatus = "completed"
	Expired   SessionStatusStatus = "expired"
)

// Valid indicates whether the value is a known member of the SessionStatusStatus enum.
func (e SessionStatusStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Completed:
		return true
	case Expired:
		return true
	default:
		return false
	}
}

// Defines values for GetApiV1DashboardSummaryParamsDays.
const (
	N30 GetApiV1DashboardSummaryParamsDays = 30
	N7  GetApiV1DashboardSummaryParamsDays = 7
	N90 GetApiV1DashboardSummaryParamsDays = 90
)

// Valid indicates whether the value is a known member of the GetApiV1DashboardSummaryParamsDays enum.
func (e GetApiV1DashboardSummaryParamsDays) Valid() bool {
	switch e {
	case N30:
		return true
	case N7:
		return true
	case N90:
		return true
	default:
		return false
	}
}

// BloodPressureRequest defines model for BloodPressureRequest.
type BloodPressureRequest struct {
	Diastolic  int                `json:"diastolic"`
	MeasuredAt *time.Time         `json:"measured_at,omitempty"`
	Pulse      int                `json:"pulse"`
	Systolic   int                `json:"systolic"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// BloodPressureResponse defines model for BloodPressureResponse.
type BloodPressureResponse struct {
	CreatedAt  *time.Time          `json:"created_at,omitempty"`
	Diastolic  *int                `json:"diastolic,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	MeasuredAt *time.Time          `json:"measured_at,omitempty"`
	Pulse      *int                `json:"pulse,omitempty"`
	Systolic   *int                `json:"systolic,omitempty"`
	UserId     *openapi_types.UUID `json:"user_id,omitempty"`
}

// CompleteSessionRequest defines model for CompleteSessionRequest.
type CompleteSessionRequest struct {
	SessionId openapi_types.UUID `json:"session_id"`
}

// ConversationStateResponse defines model for ConversationStateResponse.
type ConversationStateResponse struct {
	// IsComplete Whether all questions have been answered
	IsComplete *bool   `json:"is_complete,omitempty"`
	QuestionId *string `json:"question_id,omitempty"`

	// QuestionText Next question in Hungarian
	QuestionText *string             `json:"question_text,omitempty"`
	SessionId    *openapi_types.UUID `json:"session_id,omitempty"`
}

// CreateMedicationRequest defines model for CreateMedicationRequest.
type CreateMedicationRequest struct {
	Dosage    string              `json:"dosage"`
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	Frequency string              `json:"frequency"`
	Name      string              `json:"name"`
	Notes     *string             `json:"notes,omitempty"`
	StartDate openapi_types.Date  `json:"start_date"`
	UserId    openapi_types.UUID  `json:"user_id"`
}

// DailyMetrics defines model for DailyMetrics.
type DailyMetrics struct {
	Date         *openapi_types.Date `json:"date,omitempty"`
	EnergyLevel  *string             `json:"energy_level,omitempty"`
	Mood         *string             `json:"mood,omitempty"`
	PainLevel    *int                `json:"pain_level,omitempty"`
	SleepQuality *string             `json:"sleep_quality,omitempty"`
}

// DashboardSummary defines model for DashboardSummary.
type DashboardSummary struct {
	AveragePain  *float64 `json:"average_pain,omitempty"`
	CheckInCount *int     `json:"check_in_count,omitempty"`
	EnergyLevels *struct {
		High   *int `json:"high,omitempty"`
		Low    *int `json:"low,omitempty"`
		Medium *int `json:"medium,omitempty"`
	} `json:"energy_levels,omitempty"`
	MoodDistribution *struct {
		Negative *int `json:"negative,omitempty"`
		Neutral  *int `json:"neutral,omitempty"`
		Positive *int `json:"positive,omitempty"`
	} `json:"mood_distribution,omitempty"`
	Period         *string         `json:"period,omitempty"`
	TimeSeriesData *[]DailyMetrics `json:"time_series_data,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string  `json:"code"`
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// FitnessDataPoint defines model for FitnessDataPoint.
type FitnessDataPoint struct {
	DataType FitnessDataPointDataType `json:"data_type"`
	Date     openapi_types.Date       `json:"date"`
	Source   FitnessDataPointSource   `json:"source"`

	// SourceDataId Original ID from Health Connect for deduplication
	SourceDataId string               `json:"source_data_id"`
	Unit         FitnessDataPointUnit `json:"unit"`
	Value        float64              `json:"value"`
}

// FitnessDataPointDataType defines model for FitnessDataPoint.DataType.
type FitnessDataPointDataType string

// FitnessDataPointSource defines model for FitnessDataPoint.Source.
type FitnessDataPointSource string

// FitnessDataPointUnit defines model for FitnessDataPoint.Unit.
type FitnessDataPointUnit string

// FitnessSyncRequest defines model for FitnessSyncRequest.
type FitnessSyncRequest struct {
	DataPoints []FitnessDataPoint `json:"data_points"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// GenerateReportRequest defines model for GenerateReportRequest.
type GenerateReportRequest struct {
	EndDate   openapi_types.Date `json:"end_date"`
	StartDate openapi_types.Date `json:"start_date"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// HealthCheckInResponse defines model for HealthCheckInResponse.
type HealthCheckInResponse struct {
	AdditionalNotes *string                           `json:"additional_notes,omitempty"`
	CheckInDate     *openapi_types.Date               `json:"check_in_date,omitempty"`
	CreatedAt       *time.Time                        `json:"created_at,omitempty"`
	EnergyLevel     *HealthCheckInResponseEnergyLevel `json:"energy_level,omitempty"`
	GeneralFeeling  *string                           `json:"general_feeling,omitempty"`
	Id              *openapi_types.UUID               `json:"id,omitempty"`
	Meals           *struct {
		Breakfast *string `json:"breakfast,omitempty"`
		Dinner    *string `json:"dinner,omitempty"`
		Lunch     *string `json:"lunch,omitempty"`
	} `json:"meals,omitempty"`
	MedicationTaken  *HealthCheckInResponseMedicationTaken `json:"medication_taken,omitempty"`
	Mood             *HealthCheckInResponseMood            `json:"mood,omitempty"`
	PainLevel        *int                                  `json:"pain_level,omitempty"`
	PhysicalActivity *[]string                             `json:"physical_activity,omitempty"`
	SleepQuality     *HealthCheckInResponseSleepQuality    `json:"sleep_quality,omitempty"`
	Symptoms         *[]string                             `json:"symptoms,omitempty"`
	UserId           *openapi_types.UUID                   `json:"user_id,omitempty"`
}

// HealthCheckInResponseEnergyLevel defines model for HealthCheckInResponse.EnergyLevel.
type HealthCheckInResponseEnergyLevel string

// HealthCheckInResponseMedicationTaken defines model for HealthCheckInResponse.MedicationTaken.
type HealthCheckInResponseMedicationTaken string

// HealthCheckInResponseMood defines model for HealthCheckInResponse.Mood.
type HealthCheckInResponseMood string

// HealthCheckInResponseSleepQuality defines model for HealthCheckInResponse.SleepQuality.
type HealthCheckInResponseSleepQuality string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Database *HealthStatusDatabase `json:"database,omitempty"`
	Status   *HealthStatusStatus   `json:"status,omitempty"`
}

// HealthStatusDatabase defines model for HealthStatus.Database.
type HealthStatusDatabase string

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// MedicationResponse defines model for MedicationResponse.
type MedicationResponse struct {
	Active    *bool               `json:"active,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Dosage    *string             `json:"dosage,omitempty"`
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	Frequency *string             `json:"frequency,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Name      *string             `json:"name,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
	StartDate *openapi_types.Date `json:"start_date,omitempty"`
	UserId    *openapi_types.UUID `json:"user_id,omitempty"`
}

// MenstruationRequest defines model for MenstruationRequest.
type MenstruationRequest struct {
	EndDate       *openapi_types.Date               `json:"end_date,omitempty"`
	FlowIntensity *MenstruationRequestFlowIntensity `json:"flow_intensity,omitempty"`
	StartDate     openapi_types.Date                `json:"start_date"`
	Symptoms      *[]string                         `json:"symptoms,omitempty"`
	UserId        openapi_types.UUID                `json:"user_id"`
}

// MenstruationRequestFlowIntensity defines model for MenstruationRequest.FlowIntensity.
type MenstruationRequestFlowIntensity string

// MenstruationResponse defines model for MenstruationResponse.
type MenstruationResponse struct {
	CreatedAt     *time.Time                         `json:"created_at,omitempty"`
	EndDate       *openapi_types.Date                `json:"end_date,omitempty"`
	FlowIntensity *MenstruationResponseFlowIntensity `json:"flow_intensity,omitempty"`
	Id            *openapi_types.UUID                `json:"id,omitempty"`
	StartDate     *openapi_types.Date                `json:"start_date,omitempty"`
	Symptoms      *[]string                          `json:"symptoms,omitempty"`
	UserId        *openapi_types.UUID                `json:"user_id,omitempty"`
}

// MenstruationResponseFlowIntensity defines model for MenstruationResponse.FlowIntensity.
type MenstruationResponseFlowIntensity string

// ReportResponse defines model for ReportResponse.
type ReportResponse struct {
	DateRangeEnd   *openapi_types.Date   `json:"date_range_end,omitempty"`
	DateRangeStart *openapi_types.Date   `json:"date_range_start,omitempty"`
	GeneratedAt    *time.Time            `json:"generated_at,omitempty"`
	Id             *openapi_types.UUID   `json:"id,omitempty"`
	Status         *ReportResponseStatus `json:"status,omitempty"`
	UserId         *openapi_types.UUID   `json:"user_id,omitempty"`
}

// ReportResponseStatus defines model for ReportResponse.Status.
type ReportResponseStatus string

// RespondRequest defines model for RespondRequest.
type RespondRequest struct {
	// Response User's transcribed response
	Response  string             `json:"response"`
	SessionId openapi_types.UUID `json:"session_id"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	QuestionId *string `json:"question_id,omitempty"`

	// QuestionText First question in Hungarian
	QuestionText *string                `json:"question_text,omitempty"`
	SessionId    *openapi_types.UUID    `json:"session_id,omitempty"`
	StartedAt    *time.Time             `json:"started_at,omitempty"`
	Status       *SessionResponseStatus `json:"status,omitempty"`
	UserId       *openapi_types.UUID    `json:"user_id,omitempty"`
}

// SessionResponseStatus defines model for SessionResponse.Status.
type SessionResponseStatus string

// SessionStatus defines model for SessionStatus.
type SessionStatus struct {
	CompletedAt       *time.Time           `json:"completed_at,omitempty"`
	QuestionsAnswered *int                 `json:"questions_answered,omitempty"`
	SessionId         *openapi_types.UUID  `json:"session_id,omitempty"`
	StartedAt         *time.Time           `json:"started_at,omitempty"`
	Status            *SessionStatusStatus `json:"status,omitempty"`
	TotalQuestions    *int                 `json:"total_questions,omitempty"`
}

// SessionStatusStatus defines model for SessionStatus.Status.
type SessionStatusStatus string

// StartSessionRequest defines model for StartSessionRequest.
type StartSessionRequest struct {
	UserId openapi_types.UUID `json:"user_id"`
}

// UpdateMedicationRequest defines model for UpdateMedicationRequest.
type UpdateMedicationRequest struct {
	Dosage    *string             `json:"dosage,omitempty"`
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	Frequency *string             `json:"frequency,omitempty"`
	Name      *string             `json:"name,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// GetApiV1DashboardSummaryParams defines parameters for GetApiV1DashboardSummary.
type GetApiV1DashboardSummaryParams struct {
	UserId openapi_types.UUID                  `form:"user_id" json:"user_id"`
	Days   *GetApiV1DashboardSummaryParamsDays `form:"days,omitempty" json:"days,omitempty"`
}

// GetApiV1DashboardSummaryParamsDays defines parameters for GetApiV1DashboardSummary.
type GetApiV1DashboardSummaryParamsDays int

// GetApiV1HealthBloodPressureParams defines parameters for GetApiV1HealthBloodPressure.
type GetApiV1HealthBloodPressureParams struct {
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// GetApiV1HealthMedicationsParams defines parameters for GetApiV1HealthMedications.
type GetApiV1HealthMedicationsParams struct {
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// GetApiV1HealthMenstruationParams defines parameters for GetApiV1HealthMenstruation.
type GetApiV1HealthMenstruationParams struct {
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// PostApiV1CheckinCompleteJSONRequestBody defines body for PostApiV1CheckinComplete for application/json ContentType.
type PostApiV1CheckinCompleteJSONRequestBody = CompleteSessionRequest

// PostApiV1CheckinRespondJSONRequestBody defines body for PostApiV1CheckinRespond for application/json ContentType.
type PostApiV1CheckinRespondJSONRequestBody = RespondRequest

// PostApiV1CheckinStartJSONRequestBody defines body for PostApiV1CheckinStart for application/json ContentType.
type PostApiV1CheckinStartJSONRequestBody = StartSessionRequest

// PostApiV1HealthBloodPressureJSONRequestBody defines body for PostApiV1HealthBloodPressure for application/json ContentType.
type PostApiV1HealthBloodPressureJSONRequestBody = BloodPressureRequest

// PostApiV1HealthFitnessSyncJSONRequestBody defines body for PostApiV1HealthFitnessSync for application/json ContentType.
type PostApiV1HealthFitnessSyncJSONRequestBody = FitnessSyncRequest

// PostApiV1HealthMedicationsJSONRequestBody defines body for PostApiV1HealthMedications for application/json ContentType.
type PostApiV1HealthMedicationsJSONRequestBody = CreateMedicationRequest

// PutApiV1HealthMedicationsIdJSONRequestBody defines body for PutApiV1HealthMedicationsId for application/json ContentType.
type PutApiV1HealthMedicationsIdJSONRequestBody = UpdateMedicationRequest

// PostApiV1HealthMenstruationJSONRequestBody defines body for PostApiV1HealthMenstruation for application/json ContentType.
type PostApiV1HealthMenstruationJSONRequestBody = MenstruationRequest

// PostApiV1ReportsGenerateJSONRequestBody defines body for PostApiV1ReportsGenerate for application/json ContentType.
type PostApiV1ReportsGenerateJSONRequestBody = GenerateReportRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Complete check-in session
	// (POST /api/v1/checkin/complete)
	PostApiV1CheckinComplete(c *gin.Context)
	// Submit user response
	// (POST /api/v1/checkin/respond)
	PostApiV1CheckinRespond(c *gin.Context)
	// Start new check-in session
	// (POST /api/v1/checkin/start)
	PostApiV1CheckinStart(c *gin.Context)
	// Get session status
	// (GET /api/v1/checkin/status/{sessionId})
	GetApiV1CheckinStatusSessionId(c *gin.Context, sessionId openapi_types.UUID)
	// Get dashboard summary
	// (GET /api/v1/dashboard/summary)
	GetApiV1DashboardSummary(c *gin.Context, params GetApiV1DashboardSummaryParams)
	// Get blood pressure history
	// (GET /api/v1/health/blood-pressure)
	GetApiV1HealthBloodPressure(c *gin.Context, params GetApiV1HealthBloodPressureParams)
	// Log blood pressure reading
	// (POST /api/v1/health/blood-pressure)
	PostApiV1HealthBloodPressure(c *gin.Context)
	// Sync fitness data from Health Connect
	// (POST /api/v1/health/fitness-sync)
	PostApiV1HealthFitnessSync(c *gin.Context)
	// List medications
	// (GET /api/v1/health/medications)
	GetApiV1HealthMedications(c *gin.Context, params GetApiV1HealthMedicationsParams)
	// Add medication
	// (POST /api/v1/health/medications)
	PostApiV1HealthMedications(c *gin.Context)
	// Delete medication
	// (DELETE /api/v1/health/medications/{id})
	DeleteApiV1HealthMedicationsId(c *gin.Context, id openapi_types.UUID)
	// Update medication
	// (PUT /api/v1/health/medications/{id})
	PutApiV1HealthMedicationsId(c *gin.Context, id openapi_types.UUID)
	// Get menstruation history
	// (GET /api/v1/health/menstruation)
	GetApiV1HealthMenstruation(c *gin.Context, params GetApiV1HealthMenstruationParams)
	// Log menstruation data
	// (POST /api/v1/health/menstruation)
	PostApiV1HealthMenstruation(c *gin.Context)
	// Generate health report
	// (POST /api/v1/reports/generate)
	PostApiV1ReportsGenerate(c *gin.Context)
	// Download report
	// (GET /api/v1/reports/{id})
	GetApiV1ReportsId(c *gin.Context, id openapi_types.UUID)
	// Health check endpoint
	// (GET /health)
	GetHealth(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostApiV1CheckinComplete operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1CheckinComplete(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1CheckinComplete(c)
}

// PostApiV1CheckinRespond operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1CheckinRespond(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1CheckinRespond(c)
}

// PostApiV1CheckinStart operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1CheckinStart(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1CheckinStart(c)
}

// GetApiV1CheckinStatusSessionId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1CheckinStatusSessionId(c *gin.Context) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", c.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1CheckinStatusSessionId(c, sessionId)
}

// GetApiV1DashboardSummary operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1DashboardSummary(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1DashboardSummaryParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "days", c.Request.URL.Query(), &params.Days, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter days: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1DashboardSummary(c, params)
}

// GetApiV1HealthBloodPressure operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1HealthBloodPressure(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1HealthBloodPressureParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1HealthBloodPressure(c, params)
}

// PostApiV1HealthBloodPressure operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1HealthBloodPressure(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1HealthBloodPressure(c)
}

// PostApiV1HealthFitnessSync operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1HealthFitnessSync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1HealthFitnessSync(c)
}

// GetApiV1HealthMedications operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1HealthMedications(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1HealthMedicationsParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1HealthMedications(c, params)
}

// PostApiV1HealthMedications operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1HealthMedications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1HealthMedications(c)
}

// DeleteApiV1HealthMedicationsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1HealthMedicationsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiV1HealthMedicationsId(c, id)
}

// PutApiV1HealthMedicationsId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1HealthMedicationsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiV1HealthMedicationsId(c, id)
}

// GetApiV1HealthMenstruation operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1HealthMenstruation(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1HealthMenstruationParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1HealthMenstruation(c, params)
}

// PostApiV1HealthMenstruation operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1HealthMenstruation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1HealthMenstruation(c)
}

// PostApiV1ReportsGenerate operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1ReportsGenerate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1ReportsGenerate(c)
}

// GetApiV1ReportsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1ReportsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1ReportsId(c, id)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/checkin/complete", wrapper.PostApiV1CheckinComplete)
	router.POST(options.BaseURL+"/api/v1/checkin/respond", wrapper.PostApiV1CheckinRespond)
	router.POST(options.BaseURL+"/api/v1/checkin/start", wrapper.PostApiV1CheckinStart)
	router.GET(options.BaseURL+"/api/v1/checkin/status/:sessionId", wrapper.GetApiV1CheckinStatusSessionId)
	router.GET(options.BaseURL+"/api/v1/dashboard/summary", wrapper.GetApiV1DashboardSummary)
	router.GET(options.BaseURL+"/api/v1/health/blood-pressure", wrapper.GetApiV1HealthBloodPressure)
	router.POST(options.BaseURL+"/api/v1/health/blood-pressure", wrapper.PostApiV1HealthBloodPressure)
	router.POST(options.BaseURL+"/api/v1/health/fitness-sync", wrapper.PostApiV1HealthFitnessSync)
	router.GET(options.BaseURL+"/api/v1/health/medications", wrapper.GetApiV1HealthMedications)
	router.POST(options.BaseURL+"/api/v1/health/medications", wrapper.PostApiV1HealthMedications)
	router.DELETE(options.BaseURL+"/api/v1/health/medications/:id", wrapper.DeleteApiV1HealthMedicationsId)
	router.PUT(options.BaseURL+"/api/v1/health/medications/:id", wrapper.PutApiV1HealthMedicationsId)
	router.GET(options.BaseURL+"/api/v1/health/menstruation", wrapper.GetApiV1HealthMenstruation)
	router.POST(options.BaseURL+"/api/v1/health/menstruation", wrapper.PostApiV1HealthMenstruation)
	router.POST(options.BaseURL+"/api/v1/reports/generate", wrapper.PostApiV1ReportsGenerate)
	router.GET(options.BaseURL+"/api/v1/reports/:id", wrapper.GetApiV1ReportsId)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xc628bNxL/VwjeAb0DNpbzKNLTtzRuWgNNG9ht70NhCNRytGLNJbckV7EQ6H8/8LFv",
	"rrS2LCe5b5Z2yRnO/ObJkT/hVOaFFCCMxvNPWIEupNDgPnxP6BX8XYI29lMqhQHh/iRFwVlKDJNi9peW",
	"wn6n0zXkxP71TwUrPMf/mDVbz/xTPftBKamuAhG82+0STEGnihV2Mzy3NJHyRNEztCGcUUcHgV2Jdwm+",
	"FAaUINxt9XSMVWSRBrUB1fDzizTvZCno07FyBVqWKgUkpEErR3uX4GtQG5bC74JsCONkyeHpOAq0Udki",
	"bt8KGzgwcSnpBwValwpasCqULEAZ5iFHGdFGcpbaDzm5Y3mZ4/nzb88TnDPhP706T7DZFoDnmAkDGTg1",
	"5EDsznRB3LYrqXL7F6bEwDPDcsD1Km0UE5ldVJRcQ4fUixdtUi+jpPQ2wuOLDo+vowtLDWrBaIe/smR0",
	"yNouwdYKmAKK53/WC1u0k5asqoPc1PvI5V+QGkuzJ/egw4HgUwXE3FN6HWUNTzvpoMcqbr92jlTBQJhv",
	"ZV5wMHANWjMpRmGs/fMH6bq19ibKgtiA0s6Mrw0xe3TK9CINDDvb6pjsf9dg1qAQ4Ry5UzApNFqTDaAl",
	"gEBE6I9gWap5WErJgQjLRLUgHHCgnvq5gTszpP0L3JmaKGIC/VSKjChGREzX9xXmUGQO2++BBu837n2k",
	"JhlETwSCLiwiBxDFCRYlD/7WqBIiJ1i5iCbSbXRrQfI4TSGN5+sgAW2IMqP8DV5/BD/kmE4qibWP2OEm",
	"huALwvj2PRjFUh3RwdRDgACVbRccNsAnCSmXkk56sSBMHNy37XE4QLH4uyScme0ECruoUPR6KYmi12We",
	"E7UdCoZsQJEMFpa7roBkaWmN4lCU+dIzmq4hvV0wsUhl6XOC4WHaYo2oZ82ydXwhlx/jD3KgzMbE4bOY",
	"IKyWFpRZWS1L7y/6PAjIiGGbEf8voDSK8PjDQmo2tjTGTQGKedTAHbGuFM/xz0Qb9BpRstUxXNqQtdCg",
	"GGhrAy65YgZyfSjL6thFwwxRimzj3HXzsmFMlxS6rP/x5ufLize/Xf76y+KHq6tfr6JRHQxhXvXNwncM",
	"OEXfBPv/BjGNar8Qjem68qTNHpfCpfN1eu+Ec8jjuDM0G8b8yTtmBGh9QQz5IJkwUZ9CFn7dJwzCgvFP",
	"rA0UVoFrsN5KeS/jTBknOCVcWg26NEsbIlL7lKQWO4ucidJ65puY9Ka6L5/CtxlaA+FmvUilEPZkCc6k",
	"zDgsVsxESfkdHMaCM+9G2V8Vy5itWC4v0ErJHP3kCKC3ngBaSYUo0LKuCqKhQjDTZtJ7jgQvixy7fNdJ",
	"IsG3KeFOTwZUXDIbwkuIO66eo+pBIEiwUWK1V+CuluVAJHvQcr0V6XgeYNcXFkt6svUOUDiw4EeJu23W",
	"Ysf70fpvlxUWUpnRE+5LZ76A7KJFsZV6xc7rMf3WBrZLMe4KCaXMQpzwxfSsqg6Xk4/+kCqqn8dUlmbj",
	"aR08Ex94byYkm5lDAF+sALj9aspJp5dqsZxgqYDcrojH2UFalAkBatKrvBTp+oEJVV6n+wtDbkG0Rbt1",
	"LktIWzgTZRjhkyRbJZDVNnUy0SQdSZOcTNmxm2k2/Y52K+E8mZCCFuutZinhCxeiQhpa+61hjtJzTIMM",
	"tjmiVDa7J0z5gGRxAXcpcA7CTDqj3uaFkbm+H0fH1eneK9jyuIyXGGRJNHTjmguKLp2hTDcfb+IOMWzc",
	"jd1bF5Kqv28msdouS0e9V9rLWVul+IMaN5+lzp3oZL7wcjiiQKGNKvd3Fo4TK5cfF9bYhe6ZJ2fZ2iZA",
	"uaQQMtg1kM12mmHeT0pPYMcHk4Gbg/J/zP7ml6i0iUb05el2oLcqQx3TmOV1oYjIYAGCTjpGa4kTwKRF",
	"WciY92LjEfXSixyBvH2e4KpdS33M5SPx51jBW5HTUV+lWirpVpS/a1DfaGQUEfbrJdhiPrz8CI3bkS54",
	"0nAUs/+6Fz8GpCOb1e+Y0qfqVgdDvadfGoIoJAhdAMFd4aT5+AgKIh/Lr2omjrKo+lJiUV9FxO97vgqB",
	"G2kIX9Rnmtp/vLbcHrptOjrGxszq94L+X1+aDKVtv2JiJatrc5L6gtZRwj9sSNVA+w1Ijgd34H9IlsKz",
	"lfMWvgRwHU5Esky5mlAKVHBirCDQkqS3IKjrwdXuBFl96DP0ngiSgUZp66qP8GpT15V4xoROkDZSgUY2",
	"/UlNqYC2CSeICIqq6KaRL4g5Ui7u6jOLDmZ472xvtHb9ToPefLjECbYM+PM9Pzs/O7fHlgUIUjA8xy/P",
	"zs9euiLarJ3MZ6Rgs83zmeORiVn7+rGQOuJd3xN1i4IJI2LP7Fc45o1iWQbKyxHujLJm5/qUFoBOLpcU",
	"z/EHqc2bgv3x/K2nW13TYg930OZ7SbePNg4xcgu865qXRd0u6U7UvDg/fzQu4p2v6HCGl27tqpAu0xS0",
	"XpWcu0TulWcrRq1mf9aaBnJLXh1eUo/G7BL87RQa3dkeN0FSXYfVd++1AVSwsUAmmbYO7W14hG/s2j4a",
	"PR06Dsbrcpkz08lvrEnWSU6wKINE5wL7IzNrRErK5EFkhtzrRMDsZXZPDMjxyYT4DJMXaaGkxeLXisoA",
	"mQ5MJgOyLlLicPRzC4ggAR8PBIPGhQqbk5tSCWTWgFbd5PUeSHWZx4lwGstqnhis/aphn9/0rYPHwOfx",
	"cLOS83h4qBf0yezsU1h3SXeWpQwiALwCoxhswEEpLZUCYZBfj+QKkRgTXVT9CH1QmVJfV5R9/52ES8P5",
	"n59GNHB5gW1qhucu06imT+ZYtzbqQidpweBQTnxzepiFSmkPyIJUVZA4/Tze7EcwtScJRc8hWNFqcGWm",
	"m8mVgKY4FgajLgMUOFX/XYJ7FnTd9AMfrukkvnWY5Gj2obAiJTd4/jqpKr7Xycvz5D/nN8PLl5PiZyCr",
	"CITqd5CuX+orlQ7eafRar+8q1keY2ZJLSZ8VYYD0oHJ9VtoZOn06/R6riX4fjFAmsukjAPFR2wmTPJEx",
	"eLsVqqSO1syWejHFLuMvNtoNdd0FMQTf+AmoiPrq6B/X3ymSgOhA+KQs4PmpeNjzs4SumLnMsspH3zMJ",
	"6GjwZ5n1NRhQN6rBoYWu/OTJM70VaTuZ3Kvh1hjMifQbGbQ5QY7Xm7veihTo+HjjFNMLfPumg9+wn4Rt",
	"RYpW7dci41X3UGAzqqAn+tf3rRVfqXftHXqSg43clT/Iu7bEhzgbWiXTBuUdEVeqbAt+sjftauskHamR",
	"Cfcndqcx/eyTflVaHe9I31Da0tiowvba3uwT87UQhapn2VXrhfs+rthYMROpWB7dBF9FWqqNfP1JHlJM",
	"dKTrDz5FwAkuyphBlOazi+3xrW7siuSJWxn3trrS8X00KvzxH2p2zdDG5JjXWvKVBr10m3K4T7yLjLY8",
	"MOI1O+2pJvLYa0fWEj29ncIQYyNYTx76Yqo6oAiXO1a1xKAwyPuvTkkpw+3erLr3m1AQ+EEcXU2On0hH",
	"8cH0SVp68YgXJJ2Zo+i9hH2jujYNfTBlBgqqjlM14r3cWxoKUo1rp8o09rq9sMPnyiz2+bmCrrpCr7df",
	"MhG6Sz0CY5L+cPHu6PREfhRcun8csFcJXlWj3W7X30Rs5brdOvyinQiKqnlhRBSgWldu2nugOW+Y+OT3",
	"vvs6yp5zplE1iexawy8PyzfyLwS6kv6pdeuEQFD3Q5SWvK+32kBuxe0Gc9Qm3te/gA1wWeTuOsG9hRNc",
	"Ko7neG1MMZ/NuEwJX0tt5t+df3eOd0l/iw9K0jL1BjrcQc9n1uTOYEOeeSGcpTLHFuWB1cFVg+O8smar",
	"9dCRr06pG1MLpxwy9Xb/HV3u5jrsqZu96qb6cLdWxmYUSW+ZyBxjhK5Bgf9FWtilnW4NNwpay/1PC5vN",
	"/tWOMEmvEZVUHY5/N2TaUWeUzGDoxU9ygKAtETY957FzV4MqbVfsjDEYe7NXZeS7m93/AgAA//9giNL9",
	"z0QAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
