// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for FitnessDataPointDataType.
const (
	ActiveMinutes FitnessDataPointDataType = "active_minutes"
	Calories      FitnessDataPointDataType = "calories"
	Distance      FitnessDataPointDataType = "distance"
	HeartRate     FitnessDataPointDataType = "heart_rate"
	Sleep         FitnessDataPointDataType = "sleep"
	Steps         FitnessDataPointDataType = "steps"
)

// Valid indicates whether the value is a known member of the FitnessDataPointDataType enum.
func (e FitnessDataPointDataType) Valid() bool {
	switch e {
	case ActiveMinutes:
		return true
	case Calories:
		return true
	case Distance:
		return true
	case HeartRate:
		return true
	case Sleep:
		return true
	case Steps:
		return true
	default:
		return false
	}
}

// Defines values for FitnessDataPointSource.
const (
	GoogleFit     FitnessDataPointSource = "google_fit"
	HealthConnect FitnessDataPointSource = "health_connect"
)

// Valid indicates whether the value is a known member of the FitnessDataPointSource enum.
func (e FitnessDataPointSource) Valid() bool {
	switch e {
	case GoogleFit:
		return true
	case HealthConnect:
		return true
	default:
		return false
	}
}

// Defines values for FitnessDataPointUnit.
const (
	Bpm     FitnessDataPointUnit = "bpm"
	Count   FitnessDataPointUnit = "count"
	Kcal    FitnessDataPointUnit = "kcal"
	Meters  FitnessDataPointUnit = "meters"
	Minutes FitnessDataPointUnit = "minutes"
)

// Valid indicates whether the value is a known member of the FitnessDataPointUnit enum.
func (e FitnessDataPointUnit) Valid() bool {
	switch e {
	case Bpm:
		return true
	case Count:
		return true
	case Kcal:
		return true
	case Meters:
		return true
	case Minutes:
		return true
	default:
		return false
	}
}

// Defines values for HealthCheckInResponseEnergyLevel.
const (
	High   HealthCheckInResponseEnergyLevel = "high"
	Low    HealthCheckInResponseEnergyLevel = "low"
	Medium HealthCheckInResponseEnergyLevel = "medium"
)

// Valid indicates whether the value is a known member of the HealthCheckInResponseEnergyLevel enum.
func (e HealthCheckInResponseEnergyLevel) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for HealthCheckInResponseMedicationTaken.
const (
	No      HealthCheckInResponseMedicationTaken = "no"
	Partial HealthCheckInResponseMedicationTaken = "partial"
	Yes     HealthCheckInResponseMedicationTaken = "yes"
)

// Valid indicates whether the value is a known member of the HealthCheckInResponseMedicationTaken enum.
func (e HealthCheckInResponseMedicationTaken) Valid() bool {
	switch e {
	case No:
		return true
	case Partial:
		return true
	case Yes:
		return true
	default:
		return false
	}
}

// Defines values for HealthCheckInResponseMood.
const (
	Negative HealthCheckInResponseMood = "negative"
	Neutral  HealthCheckInResponseMood = "neutral"
	Positive HealthCheckInResponseMood = "positive"
)

// Valid indicates whether the value is a known member of the HealthCheckInResponseMood enum.
func (e HealthCheckInResponseMood) Valid() bool {
	switch e {
	case Negative:
		return true
	case Neutral:
		return true
	case Positive:
		return true
	default:
		return false
	}
}

// Defines values for HealthCheckInResponseSleepQuality.
const (
	Excellent HealthCheckInResponseSleepQuality = "excellent"
	Fair      HealthCheckInResponseSleepQuality = "fair"
	Good      HealthCheckInResponseSleepQuality = "good"
	Poor      HealthCheckInResponseSleepQuality = "poor"
)

// Valid indicates whether the value is a known member of the HealthCheckInResponseSleepQuality enum.
func (e HealthCheckInResponseSleepQuality) Valid() bool {
	switch e {
	case Excellent:
		return true
	case Fair:
		return true
	case Good:
		return true
	case Poor:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusDatabase.
const (
	Connected    HealthStatusDatabase = "connected"
	Disconnected HealthStatusDatabase = "disconnected"
)

// Valid indicates whether the value is a known member of the HealthStatusDatabase enum.
func (e HealthStatusDatabase) Valid() bool {
	switch e {
	case Connected:
		return true
	case Disconnected:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	Healthy   HealthStatusStatus = "healthy"
	Unhealthy HealthStatusStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// Defines values for MenstruationRequestFlowIntensity.
const (
	MenstruationRequestFlowIntensityHeavy    MenstruationRequestFlowIntensity = "heavy"
	MenstruationRequestFlowIntensityLight    MenstruationRequestFlowIntensity = "light"
	MenstruationRequestFlowIntensityModerate MenstruationRequestFlowIntensity = "moderate"
)

// Valid indicates whether the value is a known member of the MenstruationRequestFlowIntensity enum.
func (e MenstruationRequestFlowIntensity) Valid() bool {
	switch e {
	case MenstruationRequestFlowIntensityHeavy:
		return true
	case MenstruationRequestFlowIntensityLight:
		return true
	case MenstruationRequestFlowIntensityModerate:
		return true
	default:
		return false
	}
}

// Defines values for MenstruationResponseFlowIntensity.
const (
	MenstruationResponseFlowIntensityHeavy    MenstruationResponseFlowIntensity = "heavy"
	MenstruationResponseFlowIntensityLight    MenstruationResponseFlowIntensity = "light"
	MenstruationResponseFlowIntensityModerate MenstruationResponseFlowIntensity = "moderate"
)

// Valid indicates whether the value is a known member of the MenstruationResponseFlowIntensity enum.
func (e MenstruationResponseFlowIntensity) Valid() bool {
	switch e {
	case MenstruationResponseFlowIntensityHeavy:
		return true
	case MenstruationResponseFlowIntensityLight:
		return true
	case MenstruationResponseFlowIntensityModerate:
		return true
	default:
		return false
	}
}

// Defines values for ReportResponseStatus.
const (
	ReportResponseStatusCompleted  ReportResponseStatus = "completed"
	ReportResponseStatusFailed     ReportResponseStatus = "failed"
	ReportResponseStatusGenerating ReportResponseStatus = "generating"
)

// Valid indicates whether the value is a known member of the ReportResponseStatus enum.
func (e ReportResponseStatus) Valid() bool {
	switch e {
	case ReportResponseStatusCompleted:
		return true
	case ReportResponseStatusFailed:
		return true
	case ReportResponseStatusGenerating:
		return true
	default:
		return false
	}
}

// Defines values for SessionResponseStatus.
const (
	SessionResponseStatusActive    SessionResponseStatus = "active"
	SessionResponseStatusCompleted SessionResponseStatus = "completed"
	SessionResponseStatusExpired   SessionResponseStatus = "expired"
)

// Valid indicates whether the value is a known member of the SessionResponseStatus enum.
func (e SessionResponseStatus) Valid() bool {
	switch e {
	case SessionResponseStatusActive:
		return true
	case SessionResponseStatusCompleted:
		return true
	case SessionResponseStatusExpired:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatusStatus.
const (
	Active    SessionStatusStatus = "active"
	Completed SessionStatusStatus = "completed"
	Expired   SessionStatusStatus = "expired"
)

// Valid indicates whether the value is a known member of the SessionStatusStatus enum.
func (e SessionStatusStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Completed:
		return true
	case Expired:
		return true
	default:
		return false
	}
}

// Defines values for GetApiV1DashboardSummaryParamsDays.
const (
	N30 GetApiV1DashboardSummaryParamsDays = 30
	N7  GetApiV1DashboardSummaryParamsDays = 7
	N90 GetApiV1DashboardSummaryParamsDays = 90
)

// Valid indicates whether the value is a known member of the GetApiV1DashboardSummaryParamsDays enum.
func (e GetApiV1DashboardSummaryParamsDays) Valid() bool {
	switch e {
	case N30:
		return true
	case N7:
		return true
	case N90:
		return true
	default:
		return false
	}
}

// BloodPressureRequest defines model for BloodPressureRequest.
type BloodPressureRequest struct {
	Diastolic  int                `json:"diastolic"`
	MeasuredAt *time.Time         `json:"measured_at,omitempty"`
	Pulse      int                `json:"pulse"`
	Systolic   int                `json:"systolic"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// BloodPressureResponse defines model for BloodPressureResponse.
type BloodPressureResponse struct {
	CreatedAt  *time.Time          `json:"created_at,omitempty"`
	Diastolic  *int                `json:"diastolic,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	MeasuredAt *time.Time          `json:"measured_at,omitempty"`
	Pulse      *int                `json:"pulse,omitempty"`
	Systolic   *int                `json:"systolic,omitempty"`
	UserId     *openapi_types.UUID `json:"user_id,omitempty"`
}

// CompleteSessionRequest defines model for CompleteSessionRequest.
type CompleteSessionRequest struct {
	SessionId openapi_types.UUID `json:"session_id"`
}

// ConversationStateResponse defines model for ConversationStateResponse.
type ConversationStateResponse struct {
	// IsComplete Whether all questions have been answered
	IsComplete *bool   `json:"is_complete,omitempty"`
	QuestionId *string `json:"question_id,omitempty"`

	// QuestionText Next question in Hungarian
	QuestionText *string             `json:"question_text,omitempty"`
	SessionId    *openapi_types.UUID `json:"session_id,omitempty"`
}

// CreateMedicationRequest defines model for CreateMedicationRequest.
type CreateMedicationRequest struct {
	Dosage    string              `json:"dosage"`
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	Frequency string              `json:"frequency"`
	Name      string              `json:"name"`
	Notes     *string             `json:"notes,omitempty"`
	StartDate openapi_types.Date  `json:"start_date"`
	UserId    openapi_types.UUID  `json:"user_id"`
}

// DailyMetrics defines model for DailyMetrics.
type DailyMetrics struct {
	Date         *openapi_types.Date `json:"date,omitempty"`
	EnergyLevel  *string             `json:"energy_level,omitempty"`
	Mood         *string             `json:"mood,omitempty"`
	PainLevel    *int                `json:"pain_level,omitempty"`
	SleepQuality *string             `json:"sleep_quality,omitempty"`
}

// DashboardSummary defines model for DashboardSummary.
type DashboardSummary struct {
	AveragePain  *float64 `json:"average_pain,omitempty"`
	CheckInCount *int     `json:"check_in_count,omitempty"`
	EnergyLevels *struct {
		High   *int `json:"high,omitempty"`
		Low    *int `json:"low,omitempty"`
		Medium *int `json:"medium,omitempty"`
	} `json:"energy_levels,omitempty"`
	MoodDistribution *struct {
		Negative *int `json:"negative,omitempty"`
		Neutral  *int `json:"neutral,omitempty"`
		Positive *int `json:"positive,omitempty"`
	} `json:"mood_distribution,omitempty"`
	Period         *string         `json:"period,omitempty"`
	TimeSeriesData *[]DailyMetrics `json:"time_series_data,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string  `json:"code"`
	Details *string `json:"details,omitempty"`
	Message string  `json:"message"`
}

// FitnessDataPoint defines model for FitnessDataPoint.
type FitnessDataPoint struct {
	DataType FitnessDataPointDataType `json:"data_type"`
	Date     openapi_types.Date       `json:"date"`
	Source   FitnessDataPointSource   `json:"source"`

	// SourceDataId Original ID from Health Connect for deduplication
	SourceDataId string               `json:"source_data_id"`
	Unit         FitnessDataPointUnit `json:"unit"`
	Value        float64              `json:"value"`
}

// FitnessDataPointDataType defines model for FitnessDataPoint.DataType.
type FitnessDataPointDataType string

// FitnessDataPointSource defines model for FitnessDataPoint.Source.
type FitnessDataPointSource string

// FitnessDataPointUnit defines model for FitnessDataPoint.Unit.
type FitnessDataPointUnit string

// FitnessSyncRequest defines model for FitnessSyncRequest.
type FitnessSyncRequest struct {
	DataPoints []FitnessDataPoint `json:"data_points"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// GenerateReportRequest defines model for GenerateReportRequest.
type GenerateReportRequest struct {
	EndDate   openapi_types.Date `json:"end_date"`
	StartDate openapi_types.Date `json:"start_date"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// HealthCheckInResponse defines model for HealthCheckInResponse.
type HealthCheckInResponse struct {
	AdditionalNotes *string                           `json:"additional_notes,omitempty"`
	CheckInDate     *openapi_types.Date               `json:"check_in_date,omitempty"`
	CreatedAt       *time.Time                        `json:"created_at,omitempty"`
	EnergyLevel     *HealthCheckInResponseEnergyLevel `json:"energy_level,omitempty"`
	GeneralFeeling  *string                           `json:"general_feeling,omitempty"`
	Id              *openapi_types.UUID               `json:"id,omitempty"`
	Meals           *struct {
		Breakfast *string `json:"breakfast,omitempty"`
		Dinner    *string `json:"dinner,omitempty"`
		Lunch     *string `json:"lunch,omitempty"`
	} `json:"meals,omitempty"`
	MedicationTaken  *HealthCheckInResponseMedicationTaken `json:"medication_taken,omitempty"`
	Mood             *HealthCheckInResponseMood            `json:"mood,omitempty"`
	PainLevel        *int                                  `json:"pain_level,omitempty"`
	PhysicalActivity *[]string                             `json:"physical_activity,omitempty"`
	SleepQuality     *HealthCheckInResponseSleepQuality    `json:"sleep_quality,omitempty"`
	Symptoms         *[]string                             `json:"symptoms,omitempty"`
	UserId           *openapi_types.UUID                   `json:"user_id,omitempty"`
}

// HealthCheckInResponseEnergyLevel defines model for HealthCheckInResponse.EnergyLevel.
type HealthCheckInResponseEnergyLevel string

// HealthCheckInResponseMedicationTaken defines model for HealthCheckInResponse.MedicationTaken.
type HealthCheckInResponseMedicationTaken string

// HealthCheckInResponseMood defines model for HealthCheckInResponse.Mood.
type HealthCheckInResponseMood string

// HealthCheckInResponseSleepQuality defines model for HealthCheckInResponse.SleepQuality.
type HealthCheckInResponseSleepQuality string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Database *HealthStatusDatabase `json:"database,omitempty"`
	Status   *HealthStatusStatus   `json:"status,omitempty"`
}

// HealthStatusDatabase defines model for HealthStatus.Database.
type HealthStatusDatabase string

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// MedicationResponse defines model for MedicationResponse.
type MedicationResponse struct {
	Active    *bool               `json:"active,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Dosage    *string             `json:"dosage,omitempty"`
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	Frequency *string             `json:"frequency,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Name      *string             `json:"name,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
	StartDate *openapi_types.Date `json:"start_date,omitempty"`
	UserId    *openapi_types.UUID `json:"user_id,omitempty"`
}

// MenstruationRequest defines model for MenstruationRequest.
type MenstruationRequest struct {
	EndDate       *openapi_types.Date               `json:"end_date,omitempty"`
	FlowIntensity *MenstruationRequestFlowIntensity `json:"flow_intensity,omitempty"`
	StartDate     openapi_types.Date                `json:"start_date"`
	Symptoms      *[]string                         `json:"symptoms,omitempty"`
	UserId        openapi_types.UUID                `json:"user_id"`
}

// MenstruationRequestFlowIntensity defines model for MenstruationRequest.FlowIntensity.
type MenstruationRequestFlowIntensity string

// MenstruationResponse defines model for MenstruationResponse.
type MenstruationResponse struct {
	CreatedAt     *time.Time                         `json:"created_at,omitempty"`
	EndDate       *openapi_types.Date                `json:"end_date,omitempty"`
	FlowIntensity *MenstruationResponseFlowIntensity `json:"flow_intensity,omitempty"`
	Id            *openapi_types.UUID                `json:"id,omitempty"`
	StartDate     *openapi_types.Date                `json:"start_date,omitempty"`
	Symptoms      *[]string                          `json:"symptoms,omitempty"`
	UserId        *openapi_types.UUID                `json:"user_id,omitempty"`
}

// MenstruationResponseFlowIntensity defines model for MenstruationResponse.FlowIntensity.
type MenstruationResponseFlowIntensity string

// ReportResponse defines model for ReportResponse.
type ReportResponse struct {
	DateRangeEnd   *openapi_types.Date   `json:"date_range_end,omitempty"`
	DateRangeStart *openapi_types.Date   `json:"date_range_start,omitempty"`
	GeneratedAt    *time.Time            `json:"generated_at,omitempty"`
	Id             *openapi_types.UUID   `json:"id,omitempty"`
	Status         *ReportResponseStatus `json:"status,omitempty"`
	UserId         *openapi_types.UUID   `json:"user_id,omitempty"`
}

// ReportResponseStatus defines model for ReportResponse.Status.
type ReportResponseStatus string

// RespondRequest defines model for RespondRequest.
type RespondRequest struct {
	// Response User's transcribed response
	Response  string             `json:"response"`
	SessionId openapi_types.UUID `json:"session_id"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	QuestionId *string `json:"question_id,omitempty"`

	// QuestionText First question in Hungarian
	QuestionText *string                `json:"question_text,omitempty"`
	SessionId    *openapi_types.UUID    `json:"session_id,omitempty"`
	StartedAt    *time.Time             `json:"started_at,omitempty"`
	Status       *SessionResponseStatus `json:"status,omitempty"`
	UserId       *openapi_types.UUID    `json:"user_id,omitempty"`
}

// SessionResponseStatus defines model for SessionResponse.Status.
type SessionResponseStatus string

// SessionStatus defines model for SessionStatus.
type SessionStatus struct {
	CompletedAt       *time.Time           `json:"completed_at,omitempty"`
	QuestionsAnswered *int                 `json:"questions_answered,omitempty"`
	SessionId         *openapi_types.UUID  `json:"session_id,omitempty"`
	StartedAt         *time.Time           `json:"started_at,omitempty"`
	Status            *SessionStatusStatus `json:"status,omitempty"`
	TotalQuestions    *int                 `json:"total_questions,omitempty"`
}

// SessionStatusStatus defines model for SessionStatus.Status.
type SessionStatusStatus string

// StartSessionRequest defines model for StartSessionRequest.
type StartSessionRequest struct {
	UserId openapi_types.UUID `json:"user_id"`
}

// UpdateMedicationRequest defines model for UpdateMedicationRequest.
type UpdateMedicationRequest struct {
	Dosage    *string             `json:"dosage,omitempty"`
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	Frequency *string             `json:"frequency,omitempty"`
	Name      *string             `json:"name,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// PostApiV1CheckinAudioStreamParams defines parameters for PostApiV1CheckinAudioStream.
type PostApiV1CheckinAudioStreamParams struct {
	// SessionId Session ID for the check-in
	SessionId openapi_types.UUID `form:"session_id" json:"session_id"`
}

// GetApiV1DashboardSummaryParams defines parameters for GetApiV1DashboardSummary.
type GetApiV1DashboardSummaryParams struct {
	UserId openapi_types.UUID                  `form:"user_id" json:"user_id"`
	Days   *GetApiV1DashboardSummaryParamsDays `form:"days,omitempty" json:"days,omitempty"`
}

// GetApiV1DashboardSummaryParamsDays defines parameters for GetApiV1DashboardSummary.
type GetApiV1DashboardSummaryParamsDays int

// GetApiV1HealthBloodPressureParams defines parameters for GetApiV1HealthBloodPressure.
type GetApiV1HealthBloodPressureParams struct {
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// GetApiV1HealthMedicationsParams defines parameters for GetApiV1HealthMedications.
type GetApiV1HealthMedicationsParams struct {
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// GetApiV1HealthMenstruationParams defines parameters for GetApiV1HealthMenstruation.
type GetApiV1HealthMenstruationParams struct {
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// PostApiV1CheckinCompleteJSONRequestBody defines body for PostApiV1CheckinComplete for application/json ContentType.
type PostApiV1CheckinCompleteJSONRequestBody = CompleteSessionRequest

// PostApiV1CheckinRespondJSONRequestBody defines body for PostApiV1CheckinRespond for application/json ContentType.
type PostApiV1CheckinRespondJSONRequestBody = RespondRequest

// PostApiV1CheckinStartJSONRequestBody defines body for PostApiV1CheckinStart for application/json ContentType.
type PostApiV1CheckinStartJSONRequestBody = StartSessionRequest

// PostApiV1HealthBloodPressureJSONRequestBody defines body for PostApiV1HealthBloodPressure for application/json ContentType.
type PostApiV1HealthBloodPressureJSONRequestBody = BloodPressureRequest

// PostApiV1HealthFitnessSyncJSONRequestBody defines body for PostApiV1HealthFitnessSync for application/json ContentType.
type PostApiV1HealthFitnessSyncJSONRequestBody = FitnessSyncRequest

// PostApiV1HealthMedicationsJSONRequestBody defines body for PostApiV1HealthMedications for application/json ContentType.
type PostApiV1HealthMedicationsJSONRequestBody = CreateMedicationRequest

// PutApiV1HealthMedicationsIdJSONRequestBody defines body for PutApiV1HealthMedicationsId for application/json ContentType.
type PutApiV1HealthMedicationsIdJSONRequestBody = UpdateMedicationRequest

// PostApiV1HealthMenstruationJSONRequestBody defines body for PostApiV1HealthMenstruation for application/json ContentType.
type PostApiV1HealthMenstruationJSONRequestBody = MenstruationRequest

// PostApiV1ReportsGenerateJSONRequestBody defines body for PostApiV1ReportsGenerate for application/json ContentType.
type PostApiV1ReportsGenerateJSONRequestBody = GenerateReportRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Stream audio from mobile app
	// (POST /api/v1/checkin/audio-stream)
	PostApiV1CheckinAudioStream(c *gin.Context, params PostApiV1CheckinAudioStreamParams)
	// Complete check-in session
	// (POST /api/v1/checkin/complete)
	PostApiV1CheckinComplete(c *gin.Context)
	// Get question audio
	// (GET /api/v1/checkin/question-audio/{sessionId}/{questionId})
	GetApiV1CheckinQuestionAudioSessionIdQuestionId(c *gin.Context, sessionId openapi_types.UUID, questionId string)
	// Submit user response
	// (POST /api/v1/checkin/respond)
	PostApiV1CheckinRespond(c *gin.Context)
	// Start new check-in session
	// (POST /api/v1/checkin/start)
	PostApiV1CheckinStart(c *gin.Context)
	// Get session status
	// (GET /api/v1/checkin/status/{sessionId})
	GetApiV1CheckinStatusSessionId(c *gin.Context, sessionId openapi_types.UUID)
	// Get dashboard summary
	// (GET /api/v1/dashboard/summary)
	GetApiV1DashboardSummary(c *gin.Context, params GetApiV1DashboardSummaryParams)
	// Get blood pressure history
	// (GET /api/v1/health/blood-pressure)
	GetApiV1HealthBloodPressure(c *gin.Context, params GetApiV1HealthBloodPressureParams)
	// Log blood pressure reading
	// (POST /api/v1/health/blood-pressure)
	PostApiV1HealthBloodPressure(c *gin.Context)
	// Sync fitness data from Health Connect
	// (POST /api/v1/health/fitness-sync)
	PostApiV1HealthFitnessSync(c *gin.Context)
	// List medications
	// (GET /api/v1/health/medications)
	GetApiV1HealthMedications(c *gin.Context, params GetApiV1HealthMedicationsParams)
	// Add medication
	// (POST /api/v1/health/medications)
	PostApiV1HealthMedications(c *gin.Context)
	// Delete medication
	// (DELETE /api/v1/health/medications/{id})
	DeleteApiV1HealthMedicationsId(c *gin.Context, id openapi_types.UUID)
	// Update medication
	// (PUT /api/v1/health/medications/{id})
	PutApiV1HealthMedicationsId(c *gin.Context, id openapi_types.UUID)
	// Get menstruation history
	// (GET /api/v1/health/menstruation)
	GetApiV1HealthMenstruation(c *gin.Context, params GetApiV1HealthMenstruationParams)
	// Log menstruation data
	// (POST /api/v1/health/menstruation)
	PostApiV1HealthMenstruation(c *gin.Context)
	// Generate health report
	// (POST /api/v1/reports/generate)
	PostApiV1ReportsGenerate(c *gin.Context)
	// Download report
	// (GET /api/v1/reports/{id})
	GetApiV1ReportsId(c *gin.Context, id openapi_types.UUID)
	// Health check endpoint
	// (GET /health)
	GetHealth(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostApiV1CheckinAudioStream operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1CheckinAudioStream(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiV1CheckinAudioStreamParams

	// ------------- Required query parameter "session_id" -------------

	if paramValue := c.Query("session_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument session_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "session_id", c.Request.URL.Query(), &params.SessionId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter session_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1CheckinAudioStream(c, params)
}

// PostApiV1CheckinComplete operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1CheckinComplete(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1CheckinComplete(c)
}

// GetApiV1CheckinQuestionAudioSessionIdQuestionId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1CheckinQuestionAudioSessionIdQuestionId(c *gin.Context) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", c.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "questionId" -------------
	var questionId string

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", c.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter questionId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1CheckinQuestionAudioSessionIdQuestionId(c, sessionId, questionId)
}

// PostApiV1CheckinRespond operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1CheckinRespond(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1CheckinRespond(c)
}

// PostApiV1CheckinStart operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1CheckinStart(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1CheckinStart(c)
}

// GetApiV1CheckinStatusSessionId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1CheckinStatusSessionId(c *gin.Context) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", c.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1CheckinStatusSessionId(c, sessionId)
}

// GetApiV1DashboardSummary operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1DashboardSummary(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1DashboardSummaryParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "days", c.Request.URL.Query(), &params.Days, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter days: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1DashboardSummary(c, params)
}

// GetApiV1HealthBloodPressure operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1HealthBloodPressure(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1HealthBloodPressureParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1HealthBloodPressure(c, params)
}

// PostApiV1HealthBloodPressure operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1HealthBloodPressure(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1HealthBloodPressure(c)
}

// PostApiV1HealthFitnessSync operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1HealthFitnessSync(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1HealthFitnessSync(c)
}

// GetApiV1HealthMedications operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1HealthMedications(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1HealthMedicationsParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1HealthMedications(c, params)
}

// PostApiV1HealthMedications operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1HealthMedications(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1HealthMedications(c)
}

// DeleteApiV1HealthMedicationsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1HealthMedicationsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiV1HealthMedicationsId(c, id)
}

// PutApiV1HealthMedicationsId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1HealthMedicationsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiV1HealthMedicationsId(c, id)
}

// GetApiV1HealthMenstruation operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1HealthMenstruation(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1HealthMenstruationParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1HealthMenstruation(c, params)
}

// PostApiV1HealthMenstruation operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1HealthMenstruation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1HealthMenstruation(c)
}

// PostApiV1ReportsGenerate operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1ReportsGenerate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1ReportsGenerate(c)
}

// GetApiV1ReportsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1ReportsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1ReportsId(c, id)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/checkin/audio-stream", wrapper.PostApiV1CheckinAudioStream)
	router.POST(options.BaseURL+"/api/v1/checkin/complete", wrapper.PostApiV1CheckinComplete)
	router.GET(options.BaseURL+"/api/v1/checkin/question-audio/:sessionId/:questionId", wrapper.GetApiV1CheckinQuestionAudioSessionIdQuestionId)
	router.POST(options.BaseURL+"/api/v1/checkin/respond", wrapper.PostApiV1CheckinRespond)
	router.POST(options.BaseURL+"/api/v1/checkin/start", wrapper.PostApiV1CheckinStart)
	router.GET(options.BaseURL+"/api/v1/checkin/status/:sessionId", wrapper.GetApiV1CheckinStatusSessionId)
	router.GET(options.BaseURL+"/api/v1/dashboard/summary", wrapper.GetApiV1DashboardSummary)
	router.GET(options.BaseURL+"/api/v1/health/blood-pressure", wrapper.GetApiV1HealthBloodPressure)
	router.POST(options.BaseURL+"/api/v1/health/blood-pressure", wrapper.PostApiV1HealthBloodPressure)
	router.POST(options.BaseURL+"/api/v1/health/fitness-sync", wrapper.PostApiV1HealthFitnessSync)
	router.GET(options.BaseURL+"/api/v1/health/medications", wrapper.GetApiV1HealthMedications)
	router.POST(options.BaseURL+"/api/v1/health/medications", wrapper.PostApiV1HealthMedications)
	router.DELETE(options.BaseURL+"/api/v1/health/medications/:id", wrapper.DeleteApiV1HealthMedicationsId)
	router.PUT(options.BaseURL+"/api/v1/health/medications/:id", wrapper.PutApiV1HealthMedicationsId)
	router.GET(options.BaseURL+"/api/v1/health/menstruation", wrapper.GetApiV1HealthMenstruation)
	router.POST(options.BaseURL+"/api/v1/health/menstruation", wrapper.PostApiV1HealthMenstruation)
	router.POST(options.BaseURL+"/api/v1/reports/generate", wrapper.PostApiV1ReportsGenerate)
	router.GET(options.BaseURL+"/api/v1/reports/:id", wrapper.GetApiV1ReportsId)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9w8a2/bttp/heD7AjsHUOL0MnTH37Jm3QKsW5fs8mEwDFp8LHOhSJWknBiF//sBSd1F",
	"2Upsp+35Zlskn/uVj/wJxzLNpABhNJ5+wgp0JoUG9+V7Qm/gYw7a2G+xFAaE+0iyjLOYGCbF5B8thf1N",
	"xytIif30/wqWeIr/b1IfPfFP9eQHpaS6KYDg7XYbYQo6Viyzh+GphYmUB4rO0JpwRh0cBHYn3kb4WhhQ",
	"gnB31PMhVoJFGtQaVI3PL9K8k7mgz4fKDWiZqxiQkAYtHexthG9BrVkMfwiyJoyTBYfnw6iAjfIGcLuq",
	"OMApE5eSflCgda6goVaZkhkow7zKUUa0kZzF9ktKHliap3j64tuLCKdM+G+vLyJsNhngKWbCQAJODCkQ",
	"ezKdE3fsUqrUfsKUGDgzLAVc7dJGMZHYTVnONbRAvXzZBPUqCEpvAji+bOH4Jrgx16DmjLbwy3NG+6ht",
	"I2ytgCmgePp3tbEBO2rwqiRkVp0jF/9AbCzMDt8LGfYYHysg5pHcawmrT+0oQg8V3G7pHCiCHjPfyjTj",
	"YOAWtGZSDKqx9s+fJOvG3lkQBbEGpZ0Z3xpidsiU6XlcIOxsq2Wyf63ArEAhwjlyVDApNFqRNaAFgEBE",
	"6HuwKFU4LKTkQIRFotxQENgTT/XcwIPpw/4FHkwFFDGBfspFQhQjIiTrxzKzzzKn2++BFt5v2PtITRII",
	"UgSCzq1G9lQUR1jkvPC3RuUQoGDpIpqIN8GjBUnDMIU0Hq+9ALQhygzi11t+BD/kkI5KjjVJbGET0uAr",
	"wvjmPRjFYh2QwVgiQIBKNnMOa+CjmJRKSUctzAgTe89tehwOkM0/5oQzsxkBYRtkil4tJFH0Nk9TojZ9",
	"xpA1KJLA3GLXZpDMLaxBPRR5uvCIxiuI7+ZMzGOZ+5ygT0yTrQHxrFiyCm/k8j78IAXKbEzsPwsxwkpp",
	"Tpnl1SL3/qKLg4CEGLYe8P8CcqMIDz/MpGZDW0PYZKCY1xp4INaV4in+mWiD3iBKNjqklzZkzTUoBtra",
	"gEuumIFU78uyWnZRI0OUIpswdu28rB/TJYU26n9e/nx9dfn79a+/zH+4ufn1JhjVwRDmRV9vfMeAU/RN",
	"Yf/fIKZR5ReCMV2XnrQ+41q4dL5K7x1z9nkcR0N9YMifvGNGgNZXxJAPkgkT9Clk7vd9wiCsMv6NtYHM",
	"CnAF1lsp72WcKeMIx4RLK0GXZmlDRGyfktjqzjxlIreeeRbi3lj35VP4JkIrINys5rEUwlIW4UTKhMN8",
	"yUwQlD/B6VjhzNtR9lfFEmYrlusrtFQyRT85AOitB4CWUiEKNK+qgmCoEMw0kfSeI8KLLMUu33WciPBd",
	"TLiTkwEV5sya8BzCjqvjqDoqUHCwFmJ5VoFdxcseS3Zoy+1GxMN5gN2fWV3So623p4U9Cz5K3G2iFiLv",
	"R+u/XVaYSWUGKdyVznwB2UUDYiP1CtHrdfqtDWzXYtgVEkqZVXHC5+Ozqipcjib9KVVUN48pLc3G0yp4",
	"Rj7wzkYkm4nTAD5fAnD70xhKx5dqoZxgoYDcLYnXs72wKBMC1KilPBfx6okJVVql+3ND7kA0WbtxLktI",
	"WzgTZRjhozhbJpDlMVUyUScdUZ2cjDmxnWnW/Y5mK+EiGpGCZquNZjHhcxeiijS08lv9HKXjmHoZbE2i",
	"VDa7J0z5gGT1Ah5i4ByEGUWj3qSZkal+HEaH1eneK9jyOA+XGGRBNLTjmguKLp2hTNdfZ2GHWBzcjt0b",
	"F5LKz7NRqDbL0kHvFXdy1kYp/qTGzWepc0c6mS+8HA4IUGij8t2dhcPYyuX93Bq70B3z5CxZ2QQolRSK",
	"DHYFZL0ZZ5iP49Iz2PHeZGC2l//H7G9+iUIbaURfnmx7cisz1CGJWVzniogE5iDoKDIaWxwDRm1Kiox5",
	"p24cUS6dyFGAt88jXLZrqY+5fCD+HMp4y3I66KtUQyTtivIPDeobjYwiwv68AFvMF4uP0Lgd6IJHNUYh",
	"+6968UOKdGCz+h1T+lTd6sJQH+mX+kpUJAhtBYKHzHHz+BpUsHwov6qQOMiiqkuJeXUVEb7v+SoYbqQh",
	"fF7RNLb/eGux3XfbdHCMDZnVHxn9n7406XPb/sTEUpbX5iT2Ba2DhH9Yk7KB9juQFPfuwP+ULIazpfMW",
	"vgRwHU5EkkS5mlAKlHFiLCPQgsR3IKjrwVXuBFl56HP0ngiSgEZx46qP8PJQ15U4Y0JHSBupQCOb/sQm",
	"V0CbgCNEBEVldNPIF8QcKRd39bnVDmZ4h7ZLrV2/06DLD9c4whYBT9+L84vzC0u2zECQjOEpfnV+cf7K",
	"FdFm5Xg+IRmbrF9MHI5MTEhOmTzTRlmOWc2ROuBhb91z5BY7jigg3BljFWrcUpRrJhL0FyxuZXwHBkmF",
	"4lUu7oCiPOOSWI23quk4dk3xFH+Q2lxm7M8Xbz1GlxaGh+eLf1J0LKd/97DyVue6p1Ihs4KK9dgqCp5a",
	"F6U25WXYtBuzSjvz6ldPWuyz0ZnfDNp8L+mmO8RhCZjck3V7eqM6c8EEcTh1T912UdpG7WmflxcXjxoY",
	"aXuBlqAChhk2tzbHnXBa2YXO4xi0Xuacu4zztccx1IetaJk0xpbcltf7t1QzPNsIfzsGRnsIyY26lPd2",
	"HXVWMkWpXDAOiGSZFQxJrLrht6Uyzez2ruU0L+7DVvOeqDtUqBwi1lv4Hc7sjWJJAsp7IHgwygYs1+Hf",
	"bR/lgAPeqYNPHiQamJ84gXbuwiLcMw6ONXnuVkH+61TIkuuV/yrVZrQ2lnnLmXc/n4r913Q7+VQ+u6Zb",
	"i2YCAV39EQzKFJxVtZZ13VKcUUibQYo2YgBBOoOYLVlc5d497f0RWsr7W7HOO/kSxd8q/MZ7/NLB28DW",
	"8+/Xh7n3qAu2RHAQ7scmBcOAg3FktwkdEEwGaHBHfh41t0r2sY3HWP32AOiOFCVfpMy0YpNN1qryt8i1",
	"DBKt0aZ7ZlYVKrs9b1GVn8jxdmr+Z3a4wzNr4elWz9JMSetrv9o0wKtMS01GK2TVvgqro59oQwQJuN9T",
	"JtQpgqBIgcmVcLnsst3WeISmupr0RHoaqnefWVm7/aRdeYFvKh9DP4+QdRJlvD48Ncr7Nkczug8G9Bsw",
	"isEafFmUKwXCIL8fySUiISR2xm7fS7ptRNgvIFTPTq9mRQ9th5IVXFUFx+nnC666hdFetaLlSONE1zON",
	"hTaFdaE3BNnTglDZXd8UHZSUhY4uZvzqcygsSc4Nnr6Jyl7gm+jVRfSfi1n/Wv6k+tPjVUCFqjVIV4u6",
	"QqW9NbVcq/1twfoIM1lwKelZVrxasFe4vupqvY7wfPKdHbXZoYBQJpLxw2HhlzBGzHgGXpCyR6GS62jF",
	"tJFBwS7CC2vpFh2/K2IInvnZ2ID4qugflt8pkoDgq0KjsoAXp8JhxwtrbTZzmSSlj35kEtCS4M8y6Uqw",
	"0LpBCfYtdOlnEs/0RsTNZHKnhBsDkieSb2AE8+T9ScsCoMOD72NMr8DbN9X8gd0kbCNitGwuCwzePkKA",
	"9RCbHulf3zd2fKXetUP0KAcbmKJ6kndtsA9x1rdKpg1KWywuRdlk/Ghv2pbWSTquA+8+PbM7DclnF/fL",
	"0upwR3pJaUNigwLbaXuTT8zXQhTKnnxbrFfu97BgQ8VMoGI5ugm+DlwZ1Pz1lDylmGhx1xM+hsERzvKQ",
	"QeTms7Pt+FY3dHn+zK2MR1td7vA+WCs8+U81u3qcb3TMa2z5SoNevIk5PCbeBYYenxjx6pN2VBNpaNmB",
	"tURHbqcwxNBw7rOHvpCo9gjC5Y5lLdErDNLu0jEpZTH3MSkv20YUBH5EU5fvFJ1IRuFXlkZJ6eURL0ha",
	"06jBewm7oryrLPpgyvQEVJJTNuI93xsSKrgalk6Zaex0e8UJnyuz2OXnMro8+DKx4PSHq3cHpyfyXnDp",
	"/lJmpxC8qAa73a6/idjSdbt18V8nRFBUvkmCiAJUycq9B9STnDdMfPK5hl0dZY8506h8R8W1hl/t52/g",
	"z2XanP6pceuEQFD3imKD37cbbSC17HYjm2od7utfwRq4zFJ3neBW4QjniuMpXhmTTScTLmPCV1Kb6XcX",
	"313g/nX6ByVpHnsD7Z+gpxNrcuewJmeeCeexTLHV8gLV3lWDw7y0Ziv1oiNfUqlrUyuo7CP1dvcdXeom",
	"/izV9VlVU71/WiNjM4rEd0wkDjFCV6DAv6tcnNJMt/oHFVJL/Uvn9WH/akaYqNOIisoOx79rMM2oMwim",
	"Nw7pJ5VA0AYL657zEN3lCGPTFTtjLIy9Pqs08u1s+98AAAD//+PU53DpSgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
